import type { Country } from "./types"

export const COUNTRIES: Country[] = [
  { code: "us", name: "United States" },
  { code: "gb", name: "United Kingdom" },
  { code: "ca", name: "Canada" },
  { code: "au", name: "Australia" },
  { code: "fr", name: "France" },
  { code: "de", name: "Germany" },
  { code: "es", name: "Spain" },
  { code: "it", name: "Italy" },
  { code: "br", name: "Brazil" },
  { code: "mx", name: "Mexico" },
  { code: "ar", name: "Argentina" },
  { code: "jp", name: "Japan" },
  { code: "kr", name: "South Korea" },
  { code: "cn", name: "China" },
  { code: "in", name: "India" },
  { code: "nl", name: "Netherlands" },
  { code: "se", name: "Sweden" },
  { code: "no", name: "Norway" },
  { code: "dk", name: "Denmark" },
  { code: "fi", name: "Finland" },
]

export const MUSIC_GENRES = [
  "Rock",
  "Jazz",
  "Pop",
  "Classical",
  "Samba",
  "Flamenco",
  "Hip-Hop",
  "Electronic",
  "R&B",
  "Country",
  "Blues",
  "Reggae",
  "Metal",
  "Punk",
  "Indie",
  "Folk",
]

export const LANGUAGES = [
  "English",
  "Spanish",
  "French",
  "Portuguese",
  "German",
  "Italian",
  "Japanese",
  "Korean",
  "Mandarin",
  "Hindi",
  "Dutch",
  "Swedish",
  "Norwegian",
  "Danish",
  "Finnish",
  "Russian",
  "Arabic",
]
